apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
      - name: message-service
        image: lab2-microservices-message-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres:5432/messagedb
        - name: SPRING_RABBITMQ_HOST
          value: rabbitmq
        - name: GRPC_CLIENT_USER_SERVICE_ADDRESS
          value: static://user-service:9090
