server.port=8080
spring.application.name=bff
spring.security.oauth2.client.registration.authservice.client-id=gateway-client
spring.security.oauth2.client.registration.authservice.client-secret=secret
spring.security.oauth2.client.registration.authservice.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.authservice.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.authservice.scope=user.read,user.write,message.read,message.write,openid
spring.security.oauth2.client.provider.authservice.authorization-uri=http://auth-service:9000/oauth2/authorize
spring.security.oauth2.client.provider.authservice.token-uri=http://auth-service:9000/oauth2/token
spring.security.oauth2.client.provider.authservice.jwk-set-uri=http://auth-service:9000/oauth2/jwks
spring.security.oauth2.client.provider.authservice.user-info-uri=http://auth-service:9000/userinfo
spring.security.oauth2.client.provider.authservice.user-name-attribute=sub
spring.security.oauth2.client.provider.authservice.issuer-uri=
logging.level.org.springframework.security=DEBUG
